"""setup commit table

Revision ID: d662c7e2656e
Revises:
Create Date: 2025-04-25 21:05:00.051210

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d662c7e2656e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commit",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("commit_hash", sa.String(length=255), nullable=False),
        sa.Column("author_name", sa.String(length=128), nullable=False),
        sa.Column("author_email", sa.String(length=255), nullable=False),
        sa.Column("commit_message", sa.Text(), nullable=False),
        sa.Column("commit_date", sa.BIGINT(), nullable=False),
        sa.Column("repo_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("commit_hash"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("commit")
    # ### end Alembic commands ###
